<?php

namespace AppBundle\Repository;

/**
 * FarmerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FarmerRepository extends \Doctrine\ORM\EntityRepository
{
}
